import javafx.beans.property.IntegerProperty;
import javafx.beans.property.SimpleIntegerProperty;
import javafx.beans.property.SimpleStringProperty;
import javafx.beans.property.StringProperty;

import java.util.Objects;

/**
 * [CST338 Project2 - Slice 2: Courses &amp; Enrollment]
 * Represents a single course in the Grade &amp; Assignment Tracker.
 * A course is owned by one teacher (users.id) and can have many
 * enrollment records and many assignments.
 *
 * <p>The fields are JavaFX properties rather than plain fields. This is the
 * live-data enhancement for the slice: because the TableView binds to
 * {@code courseCodeProperty()} and friends, a cell repaints itself the moment
 * a value changes, instead of going stale until the next full reload. The
 * plain getters and setters are kept so the DAO, the tests, and the rest of
 * the app keep working unchanged.</p>
 *
 * <p>{@code capacity} is the extra-credit seat limit (an item pulled back from
 * the WILL NOT DO list). A value of 0 means unlimited, which keeps every
 * existing course and constructor working without a capacity.</p>
 *
 * @author Brent Brewington
 * @since 8/7/2026
 */
public class Course {

    /** 0 in a capacity field means "no limit", so old data needs no migration. */
    public static final int UNLIMITED = 0;

    private final IntegerProperty courseId = new SimpleIntegerProperty(this, "courseId", 0);
    private final StringProperty courseCode = new SimpleStringProperty(this, "courseCode", "");
    private final StringProperty courseName = new SimpleStringProperty(this, "courseName", "");
    private final StringProperty description = new SimpleStringProperty(this, "description", "");
    private final IntegerProperty teacherId = new SimpleIntegerProperty(this, "teacherId", 0);
    private final IntegerProperty capacity = new SimpleIntegerProperty(this, "capacity", UNLIMITED);

    /** Set once by SQLite, never edited in the UI, so a plain field is enough. */
    private String created;

    /**
     * Display-only value filled in by CourseDao when it joins the users table.
     * It is not stored in the courses table and is intentionally left out of
     * equals() and hashCode() so two rows that hold the same data still match.
     */
    private final StringProperty teacherName = new SimpleStringProperty(this, "teacherName", "");

    /**
     * Creates a new, unlimited course that has not been saved yet.
     *
     * @param courseCode  short course code, for example CST338
     * @param courseName  full course title
     * @param description optional course description
     * @param teacherId   users.id of the teacher who owns the course
     */
    public Course(String courseCode, String courseName, String description, int teacherId) {
        this(courseCode, courseName, description, teacherId, UNLIMITED);
    }

    /**
     * Creates a new course, with a seat limit, that has not been saved yet.
     *
     * @param courseCode  short course code, for example CST338
     * @param courseName  full course title
     * @param description optional course description
     * @param teacherId   users.id of the teacher who owns the course
     * @param capacity    seat limit, or {@link #UNLIMITED} for no limit
     */
    public Course(String courseCode, String courseName, String description,
                  int teacherId, int capacity) {
        this(0, courseCode, courseName, description, teacherId, capacity, null);
    }

    /**
     * Creates an unlimited course that already exists in the database.
     * Kept for callers that predate the capacity column.
     *
     * @param courseId    primary key from the courses table
     * @param courseCode  short course code, for example CST338
     * @param courseName  full course title
     * @param description optional course description
     * @param teacherId   users.id of the teacher who owns the course
     * @param created     timestamp generated by SQLite
     */
    public Course(int courseId, String courseCode, String courseName, String description,
                  int teacherId, String created) {
        this(courseId, courseCode, courseName, description, teacherId, UNLIMITED, created);
    }

    /**
     * Full constructor for a course that already exists in the database.
     *
     * @param courseId    primary key from the courses table
     * @param courseCode  short course code, for example CST338
     * @param courseName  full course title
     * @param description optional course description
     * @param teacherId   users.id of the teacher who owns the course
     * @param capacity    seat limit, or {@link #UNLIMITED} for no limit
     * @param created     timestamp generated by SQLite
     */
    public Course(int courseId, String courseCode, String courseName, String description,
                  int teacherId, int capacity, String created) {
        setCourseId(courseId);
        setCourseCode(courseCode);
        setCourseName(courseName);
        setDescription(description);
        setTeacherId(teacherId);
        setCapacity(capacity);
        this.created = created;
    }

    // ---- courseId -------------------------------------------------------

    public int getCourseId() {
        return courseId.get();
    }

    /**
     * Sets the course ID. A new course uses 0 until the database assigns a key.
     *
     * @param courseId the ID to store
     * @throws IllegalArgumentException if the ID is negative
     */
    public void setCourseId(int courseId) {
        if (courseId < 0) {
            throw new IllegalArgumentException("Course ID cannot be negative.");
        }
        this.courseId.set(courseId);
    }

    public IntegerProperty courseIdProperty() {
        return courseId;
    }

    // ---- courseCode -----------------------------------------------------

    public String getCourseCode() {
        return courseCode.get();
    }

    /**
     * Sets the course code and stores it in upper case so CST338 and cst338
     * are treated as the same code.
     *
     * @param courseCode the code to store
     * @throws IllegalArgumentException if the code is null or blank
     */
    public void setCourseCode(String courseCode) {
        if (courseCode == null || courseCode.isBlank()) {
            throw new IllegalArgumentException("Course code is required.");
        }
        this.courseCode.set(courseCode.trim().toUpperCase());
    }

    public StringProperty courseCodeProperty() {
        return courseCode;
    }

    // ---- courseName -----------------------------------------------------

    public String getCourseName() {
        return courseName.get();
    }

    /**
     * Sets the course title.
     *
     * @param courseName the title to store
     * @throws IllegalArgumentException if the title is null or blank
     */
    public void setCourseName(String courseName) {
        if (courseName == null || courseName.isBlank()) {
            throw new IllegalArgumentException("Course name is required.");
        }
        this.courseName.set(courseName.trim());
    }

    public StringProperty courseNameProperty() {
        return courseName;
    }

    // ---- description ----------------------------------------------------

    public String getDescription() {
        return description.get();
    }

    /**
     * Sets the optional description. A null description is stored as an
     * empty string so the rest of the app never has to null check it.
     *
     * @param description the description to store
     */
    public void setDescription(String description) {
        this.description.set((description == null) ? "" : description.trim());
    }

    public StringProperty descriptionProperty() {
        return description;
    }

    // ---- teacherId ------------------------------------------------------

    public int getTeacherId() {
        return teacherId.get();
    }

    /**
     * Sets the teacher who owns this course.
     *
     * @param teacherId users.id of a user whose role is TEACHER
     * @throws IllegalArgumentException if the ID is zero or negative
     */
    public void setTeacherId(int teacherId) {
        if (teacherId <= 0) {
            throw new IllegalArgumentException("A teacher must be selected for the course.");
        }
        this.teacherId.set(teacherId);
    }

    public IntegerProperty teacherIdProperty() {
        return teacherId;
    }

    // ---- capacity (extra credit) ---------------------------------------

    public int getCapacity() {
        return capacity.get();
    }

    /**
     * Sets the seat limit for the course.
     *
     * @param capacity the seat limit, or {@link #UNLIMITED} (0) for no limit
     * @throws IllegalArgumentException if the value is negative
     */
    public void setCapacity(int capacity) {
        if (capacity < 0) {
            throw new IllegalArgumentException("Course capacity cannot be negative.");
        }
        this.capacity.set(capacity);
    }

    public IntegerProperty capacityProperty() {
        return capacity;
    }

    /**
     * True when this course has a real seat limit rather than being unlimited.
     *
     * @return true if capacity is greater than zero
     */
    public boolean hasCapacityLimit() {
        return getCapacity() > UNLIMITED;
    }

    // ---- created (read only) -------------------------------------------

    public String getCreated() {
        return created;
    }

    // ---- teacherName (display only) ------------------------------------

    public String getTeacherName() {
        return teacherName.get();
    }

    /**
     * Stores the teacher's display name supplied by CourseDao.
     *
     * @param teacherName the name to show in the Teacher column
     */
    public void setTeacherName(String teacherName) {
        this.teacherName.set(teacherName == null ? "" : teacherName);
    }

    public StringProperty teacherNameProperty() {
        return teacherName;
    }

    // ---- identity -------------------------------------------------------

    @Override
    public boolean equals(Object o) {
        if (!(o instanceof Course course)) {
            return false;
        }
        return getCourseId() == course.getCourseId()
                && getTeacherId() == course.getTeacherId()
                && getCapacity() == course.getCapacity()
                && Objects.equals(getCourseCode(), course.getCourseCode())
                && Objects.equals(getCourseName(), course.getCourseName())
                && Objects.equals(getDescription(), course.getDescription());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getCourseId(), getCourseCode(), getCourseName(),
                getDescription(), getTeacherId(), getCapacity());
    }

    @Override
    public String toString() {
        return "Course{"
                + "courseId=" + getCourseId()
                + ", courseCode='" + getCourseCode() + '\''
                + ", courseName='" + getCourseName() + '\''
                + ", description='" + getDescription() + '\''
                + ", teacherId=" + getTeacherId()
                + ", capacity=" + getCapacity()
                + ", created='" + created + '\''
                + '}';
    }
}
