import java.util.Objects;

/**
 * [CST338 Project2 - Slice 2: Courses &amp; Enrollment]
 * Represents a single course in the Grade &amp; Assignment Tracker.
 * A course is owned by one teacher (users.id) and can have many
 * enrollment records and many assignments.
 *
 * @author Brent Brewington
 * @since 7/30/2026
 */
public class Course {

    private int courseId;
    private String courseCode;
    private String courseName;
    private String description;
    private int teacherId;
    private String created;

    /**
     * Display-only value filled in by CourseDao when it joins the users table.
     * It is not stored in the courses table and is intentionally left out of
     * equals() and hashCode() so two rows that hold the same data still match.
     */
    private String teacherName;

    /**
     * Creates a new course that has not been saved to the database yet.
     * Delegates to the full constructor through constructor chaining.
     *
     * @param courseCode  short course code, for example CST338
     * @param courseName  full course title
     * @param description optional course description
     * @param teacherId   users.id of the teacher who owns the course
     */
    public Course(String courseCode, String courseName, String description, int teacherId) {
        this(0, courseCode, courseName, description, teacherId, null);
    }

    /**
     * Creates a course that already exists in the database.
     *
     * @param courseId    primary key from the courses table
     * @param courseCode  short course code, for example CST338
     * @param courseName  full course title
     * @param description optional course description
     * @param teacherId   users.id of the teacher who owns the course
     * @param created     timestamp generated by SQLite
     */
    public Course(int courseId, String courseCode, String courseName, String description,
                  int teacherId, String created) {
        setCourseId(courseId);
        setCourseCode(courseCode);
        setCourseName(courseName);
        setDescription(description);
        setTeacherId(teacherId);
        this.created = created;
    }

    public int getCourseId() {
        return courseId;
    }

    /**
     * Sets the course ID. A new course uses 0 until the database assigns a key.
     *
     * @param courseId the ID to store
     * @throws IllegalArgumentException if the ID is negative
     */
    public void setCourseId(int courseId) {
        if (courseId < 0) {
            throw new IllegalArgumentException("Course ID cannot be negative.");
        }
        this.courseId = courseId;
    }

    public String getCourseCode() {
        return courseCode;
    }

    /**
     * Sets the course code and stores it in upper case so CST338 and cst338
     * are treated as the same code.
     *
     * @param courseCode the code to store
     * @throws IllegalArgumentException if the code is null or blank
     */
    public void setCourseCode(String courseCode) {
        if (courseCode == null || courseCode.isBlank()) {
            throw new IllegalArgumentException("Course code is required.");
        }
        this.courseCode = courseCode.trim().toUpperCase();
    }

    public String getCourseName() {
        return courseName;
    }

    /**
     * Sets the course title.
     *
     * @param courseName the title to store
     * @throws IllegalArgumentException if the title is null or blank
     */
    public void setCourseName(String courseName) {
        if (courseName == null || courseName.isBlank()) {
            throw new IllegalArgumentException("Course name is required.");
        }
        this.courseName = courseName.trim();
    }

    public String getDescription() {
        return description;
    }

    /**
     * Sets the optional description. A null description is stored as an
     * empty string so the rest of the app never has to null check it.
     *
     * @param description the description to store
     */
    public void setDescription(String description) {
        this.description = (description == null) ? "" : description.trim();
    }

    public int getTeacherId() {
        return teacherId;
    }

    /**
     * Sets the teacher who owns this course.
     *
     * @param teacherId users.id of a user whose role is TEACHER
     * @throws IllegalArgumentException if the ID is zero or negative
     */
    public void setTeacherId(int teacherId) {
        if (teacherId <= 0) {
            throw new IllegalArgumentException("A teacher must be selected for the course.");
        }
        this.teacherId = teacherId;
    }

    public String getCreated() {
        return created;
    }

    public String getTeacherName() {
        return teacherName;
    }

    /**
     * Stores the teacher's display name supplied by CourseDao.
     *
     * @param teacherName the name to show in the Teacher column
     */
    public void setTeacherName(String teacherName) {
        this.teacherName = teacherName;
    }

    @Override
    public boolean equals(Object o) {
        if (!(o instanceof Course course)) {
            return false;
        }
        return getCourseId() == course.getCourseId()
                && getTeacherId() == course.getTeacherId()
                && Objects.equals(getCourseCode(), course.getCourseCode())
                && Objects.equals(getCourseName(), course.getCourseName())
                && Objects.equals(getDescription(), course.getDescription());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getCourseId(), getCourseCode(), getCourseName(),
                getDescription(), getTeacherId());
    }

    @Override
    public String toString() {
        return "Course{"
                + "courseId=" + courseId
                + ", courseCode='" + courseCode + '\''
                + ", courseName='" + courseName + '\''
                + ", description='" + description + '\''
                + ", teacherId=" + teacherId
                + ", created='" + created + '\''
                + '}';
    }
}
