import java.sql.*;

/**
 * Manages the shared SQLite database connection and creates
 * the application's database tables.
 *
 * @author Yoko Mohr
 * @since 7/21/2026
 */

public class DatabaseManager {
    // JDBC URL for the local SQLite database file.
    private static final String DB_URL = "jdbc:sqlite:app.db";

    // Stores the single DatabaseManager instance used by the application.
    private static DatabaseManager instance;
    // Shared database connection used throughout the application.
    private Connection connection;

    // Opens the SQLite connection and creates the required tables.
    // The constructor is private so outside classes cannot create additional
    // DatabaseManager objects.
    private DatabaseManager() {
        try {
            connection = DriverManager.getConnection(DB_URL);
            try (Statement stmt = connection.createStatement()) {

                // Enable SQLite foreign key constraint enforcement
                // for the shared application connection.
                stmt.execute("PRAGMA foreign_keys = ON");
            }
            System.out.println("Database connected.");
            createTables();
        } catch (SQLException e) {
            System.out.println("Connection failed: " + e.getMessage());
        }
    }

    // Returns the shared DatabaseManager instance.
    // The instance is created only the first time this method is called.
    public static DatabaseManager getInstance() {
        if (instance == null) {
            instance = new DatabaseManager();
        }
        return instance;
    }

    // Closes the shared database connection and resets the Singleton instance.
    public void close() {
        try {
            if (connection != null && !connection.isClosed()) {
                connection.close();
            }
        } catch (SQLException e) {
            System.out.println("Failed to close: " + e.getMessage());
        }
        finally {
            connection = null;
            instance = null;
        }
    }

    public Connection getConnection() {
        return connection;
    }

    /**
     * Creates all database tables required by the application.
     * Each table is created by its own helper method.
     */

    private void createTables() {
        createUsersTable();

        // Brent
        createCoursesTable();

        // Jordan
        createAssignmentsTable();

        // Jit
        createGradesTable();

        // Jit 
        createAttendanceTable();
    }

    /**
     * Creates the Slice 2 tables (courses and enrollment) and turns on
     * foreign key enforcement, which SQLite leaves off by default.
     */
    private void createCoursesTable() {
        try {
            CourseSchema.create(connection);
            System.out.println("Courses and enrollment tables ready.");
        } catch (SQLException e) {
            throw new RuntimeException(
                    "Database initialization failed; tables were not created.", e);
        }
    }

    /**
     * Creates the users table if it does not already exist.
     * The id is an auto-generated primary key. Usernames and emails
     * are required, unique, and case-insensitive. The role is limited
     * to STUDENT or TEACHER, and the creation time is generated by SQLite.
     */
    private void createUsersTable() {
        String sql = """
                CREATE TABLE IF NOT EXISTS users (
                    id INTEGER PRIMARY KEY AUTOINCREMENT,
                    username TEXT NOT NULL UNIQUE COLLATE NOCASE,
                    first_name TEXT NOT NULL,
                    last_name TEXT NOT NULL,
                    email TEXT NOT NULL UNIQUE COLLATE NOCASE,
                    password TEXT NOT NULL,
                    role TEXT NOT NULL
                        CHECK (role IN ('STUDENT', 'TEACHER')),
                    created TEXT DEFAULT (datetime('now'))
                )
                """;
        try (Statement stmt = connection.createStatement()) {
            stmt.execute(sql);
            System.out.println("Users table ready.");
        } catch (SQLException e) {
            System.out.println("createUsersTable failed: " + e.getMessage());
        }
    }

private void createAssignmentsTable()
{
    String sql = """
        CREATE TABLE IF NOT EXISTS assignments (
            assignment_id INTEGER PRIMARY KEY AUTOINCREMENT,
            course_id INTEGER NOT NULL,
            title TEXT NOT NULL,
            description TEXT,
            due_date TEXT NOT NULL,
            points_possible INTEGER NOT NULL
                CHECK (points_possible >= 0),
            FOREIGN KEY (course_id)
                REFERENCES courses(course_id)
                ON DELETE CASCADE
        )
        """;

    try (Statement stmt = connection.createStatement())
    {
        stmt.execute(sql);
        System.out.println("Assignments table ready.");
    }
    catch (SQLException e)
    {
        System.out.println(
                "createAssignmentsTable failed: "
                        + e.getMessage()
        );
    }
}   
    /**
    * @author Jit Tran
    * @since 08/05/2026
    */
    private void createGradesTable() {
        try {
            GradeSchema.create(connection);
            System.out.println("Grades table ready");
        } catch(SQLException e){
            System.out.println("createGradesTable failed: " + e.getMessage());
        }
    }

    /**
    * @author Jit Tran
    * @since 08/10/2026
    */
    private void createAttendanceTable() {
        try {
            AttendanceSchema.create(connection);
            System.out.println("Attendance table ready");
        } catch (SQLException e) {
            System.out.println("createAttendanceTable failed: " + e.getMessage());
        }
    }

}
