import java.util.Objects;

/**
 * [CST338 Project2 - Slice 2: Courses &amp; Enrollment]
 * Represents one row in the enrollment junction table, which links a
 * student (users.id) to a course (courses.course_id).
 *
 * @author Brent Brewington
 * @since 7/30/2026
 */
public class Enrollment {

    private int enrollmentId;
    private int courseId;
    private int studentId;
    private String enrolledDate;

    /**
     * Creates an enrollment that has not been saved to the database yet.
     * Delegates to the full constructor through constructor chaining.
     *
     * @param courseId  courses.course_id the student is joining
     * @param studentId users.id of the student being enrolled
     */
    public Enrollment(int courseId, int studentId) {
        this(0, courseId, studentId, null);
    }

    /**
     * Creates an enrollment record that already exists in the database.
     *
     * @param enrollmentId primary key from the enrollment table
     * @param courseId     courses.course_id the student is joining
     * @param studentId    users.id of the student being enrolled
     * @param enrolledDate timestamp generated by SQLite
     */
    public Enrollment(int enrollmentId, int courseId, int studentId, String enrolledDate) {
        setEnrollmentId(enrollmentId);
        setCourseId(courseId);
        setStudentId(studentId);
        this.enrolledDate = enrolledDate;
    }

    public int getEnrollmentId() {
        return enrollmentId;
    }

    /**
     * Sets the enrollment ID. A new record uses 0 until the database assigns a key.
     *
     * @param enrollmentId the ID to store
     * @throws IllegalArgumentException if the ID is negative
     */
    public void setEnrollmentId(int enrollmentId) {
        if (enrollmentId < 0) {
            throw new IllegalArgumentException("Enrollment ID cannot be negative.");
        }
        this.enrollmentId = enrollmentId;
    }

    public int getCourseId() {
        return courseId;
    }

    /**
     * Sets the course side of the relationship.
     *
     * @param courseId courses.course_id
     * @throws IllegalArgumentException if the ID is zero or negative
     */
    public void setCourseId(int courseId) {
        if (courseId <= 0) {
            throw new IllegalArgumentException("Course ID must be greater than zero.");
        }
        this.courseId = courseId;
    }

    public int getStudentId() {
        return studentId;
    }

    /**
     * Sets the student side of the relationship.
     *
     * @param studentId users.id of a user whose role is STUDENT
     * @throws IllegalArgumentException if the ID is zero or negative
     */
    public void setStudentId(int studentId) {
        if (studentId <= 0) {
            throw new IllegalArgumentException("Student ID must be greater than zero.");
        }
        this.studentId = studentId;
    }

    public String getEnrolledDate() {
        return enrolledDate;
    }

    @Override
    public boolean equals(Object o) {
        if (!(o instanceof Enrollment that)) {
            return false;
        }
        return getEnrollmentId() == that.getEnrollmentId()
                && getCourseId() == that.getCourseId()
                && getStudentId() == that.getStudentId();
    }

    @Override
    public int hashCode() {
        return Objects.hash(getEnrollmentId(), getCourseId(), getStudentId());
    }

    @Override
    public String toString() {
        return "Enrollment{"
                + "enrollmentId=" + enrollmentId
                + ", courseId=" + courseId
                + ", studentId=" + studentId
                + ", enrolledDate='" + enrolledDate + '\''
                + '}';
    }
}
